[[redirects]]
  from = "/docs"
  to = "https://continuedev.netlify.app/intro"
  status = 200
  
[[redirects]]
  from = "/docs/*"
  to = "https://continuedev.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/docs"
  to = "https://continuedev.netlify.app/intro"
  status = 200