[[redirects]]
  from = "/docs"
  to = "https://continuedev.netlify.app/intro"
  status = 200
  
[[redirects]]
  from = "/docs/*"
  to = "https://continuedev.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/docs"
  to = "https://continuedev.netlify.app/intro"
  status = 200

[[redirects]]
  from = "https://continue.dev/privacy"
  to = "https://continue.dev/public/privacy/notice.pdf"
  status = 200

[[redirects]]
  from = "https://www.blog.continue.dev/*"
  to = "https://blog.continue.dev/:splat"
  status = 301
  force= true